version: '3'

services:
  sistemaantenado:
    image: sistemaantenado:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sistemaantenado$
    volumes:
      - C:\Users\RenatoLima\Documents\ServerProjects\antenado\Antenado\SistemaAntenado:/app
      - C:\Users\RenatoLima\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_sistemaantenado$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sistemaantenado$ bin/Debug/netcoreapp2.0/SistemaAntenado.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
